### ISSUE TITLE
Cannot generate docs for source .bal files

### ISSUE THREAD

**Issue by lasinducharith** [ballerinalang/docerina#143] opened 2017-12-21 08:29 UTC
Issue 1
=======
$ ballerina doc services/
docerina: API documentation generation for sources - [services/]
ballerina: source package/file cannot be null

Issue 2
======
$ballerina doc Main.bal 
docerina: API documentation generation for sources - [Main.bal]

The docs are not being generated. Im using the latest builds from master as of today.

**Comment by NatashaWso2** [comment] 2017-12-22 06:16
Issue 1 is a duplicate of : https://github.com/ballerinalang/docerina/issues/142

**Comment by NatashaWso2** [comment] 2017-12-22 08:08
This issue can be closed since issue 2 is fixed with #144 and issue 1 is a duplicate of #142

**Closed by NatashaWso2** 2017-12-22 08:08 UTC
